### ISSUE TITLE
 Dependency installation failed

### ISSUE THREAD

**Issue by nd0nd0** [EddyVinck/my-prismic-remix-site#1]
Running `npx @slicemachine/init` with Remix produces the error below.

`npm info using npm@9.8.1
npm info using node@v18.17.1
npm http fetch GET 200 https://registry.npmjs.org/slice-machine-ui 260ms (cache hit)
npm http fetch GET 404 https://registry.npmjs.org/@slicemachine%2fadapter-universal 582ms (cache skip)
npm http fetch GET 404 https://registry.npmjs.org/@slicemachine%2fadapter-universal 121ms (cache skip)
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@slicemachine%2fadapter-universal - Not found
npm ERR! 404
npm ERR! 404  '@slicemachine/adapter-universal@latest' is not in this registry.
`

Does slicemachine support remix?

**Comment by EddyVinck** [comment]
Hey @nd0nd0! I used Slicemachine when working on this project last year and I haven't really been working with Remix in the meantime. Because of that, I am not sure if any changes to either Slicemachine or Remix could be the problem here.

Judging from your 404 error it seems some packages can't be found on the NPM registry. It doesn't really seem related to this repo.

I assume you are following the blog post https://prismic.io/blog/remix-tutorial-headless-cms? Maybe you can try cloning this repo to see if you can use Slicemachine. It used to work when I wrote the blog post.

**Comment by nd0nd0** [comment]
Yes, I was following the blog post on Prismic. I later found out the team is working on a universal adapter, so it is now down to waiting without a workaround. Thank you @EddyVinck taking the time to respond to this.
